---
# tasks file for wsl-devcontainers

- name: Install apt packages

  become: yes
  apt:
    name:
      - gcc
      - make
      - g++
      - libsecret-1-0
      - libsm6
    update_cache: yes
    state: present

- name: Create temp node link
  become: true
  shell: >
    ln -s /home/{{ ansible_user_id }}/.nvm/versions/node/v18.16.0/bin/node /usr/bin/node

- name: "Install NPM-distributed command-line tools"
  debugger: on_failed
  become: false
  npm:
    global: yes
    name: "{{ item }}"
    executable: /home/{{ ansible_user_id }}/.nvm/versions/node/v18.16.0/bin/npm
  with_items:
    - "@devcontainers/cli"

- name: remove temp node link
  become: true
  shell: >
    rm /usr/bin/node

# - name: Install NPM-distributed command-line tools
#   ansible.builtin.shell: >
#     npm install {{ item }} -g
#   with_items:
#     - "@devcontainers/cli"