---
# tasks file for wsl-devcontainers

- name: Install apt packages

  become: yes
  apt:
    name:
      - gcc
      - make
      - g++
      - libsecret-1-0
      - libsm6
    update_cache: yes
    state: present

- name: Create temp node symbolic link 
  become: true
  ansible.builtin.file:
    src: '/home/{{ ansible_user_id }}/.nvm/versions/node/v{{ node_version }}/bin/node'
    dest: '/usr/bin/node'
    state: link

- name: "Install NPM-distributed command-line tools"
  debugger: on_failed
  become: false
  npm:
    global: yes
    name: "{{ item }}"
    executable: /home/{{ ansible_user_id }}/.nvm/versions/node/v{{ node_version }}/bin/npm
  with_items:
    - "@devcontainers/cli"
    - "@go-task/cli"

- name:  Remove temp node symbolic link 
  become: true
  ansible.builtin.file:
    path: /usr/bin/node
    state: absent

