---
# tasks file for dev_dapr_cli
- name: "**dapr-cli** register status of /usr/local/bin/dapr"
  ansible.builtin.stat: 
    path: "/usr/local/bin/dapr"
  register: dapr_cli_status

- name: "**dapr-cli** install dapr-cli"
  when : dapr_cli_status.stat.exists == False
  block: 
    - name: Download dapr Installer
      get_url:
        url: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
        dest: /tmp/dapr-install.sh
        mode: '0755'
        force: 'yes'

    - name: install dapr cli
      shell: /tmp/dapr-install.sh
      args:
        executable: /bin/bash
