---
# tasks file for dev_nodejs
- name: "Install native apt packages"
  become: yes
  apt:
    name:
      - libsecret-1-dev
    update_cache: yes
    state: present

- name: "**node** register status of $HOME/.nvm/nvm.sh"
  ansible.builtin.stat: 
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_status

- name: "**node** install node"
  when : nvm_status.stat.exists == False
  block: 
  - name: "*node**: Download nvm install script"
    ansible.builtin.uri:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
      return_content: yes
    register: nvm_install_script

  - name: "*node** run nvm install script"
    ansible.builtin.shell: 
      "{{ nvm_install_script.content }}"
    args:
      executable: /bin/bash

- name: "**node** Install node"
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ node_version }}"


- name: "**node** set NODE_EXTRA_CA_CERTS environment variable"
  when: certs.stat.exists == True
  ansible.builtin.blockinfile:  
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    path: /home/{{ ansible_user_id }}/.profile
    block: |
      export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/wincerts.pem


- name: "**node** configure node to use certificates"
  when: certs.stat.exists == True
  become: no
  shell: |
      . {{ ansible_env.HOME }}/.nvm/nvm.sh
      npm config set cafile=/usr/local/share/ca-certificates/wincerts.pem -L user
  args:
    executable: /bin/bash