---

- name: Create a directory for any certificates
  become: yes
  ansible.builtin.file:

    path: /usr/local/share/ca-certificates/wincerts
    state: directory
    mode: '0755'

- name: "copy certificates to trusted ca path"
  become: yes
  ansible.builtin.copy:
    src: './certs/'
    dest: '/usr/local/share/ca-certificates/wincerts/'
    # owner: root
    # group: root
    mode: 0644


- name: " update trusted ca"
  ansible.builtin.shell: /usr/sbin/update-ca-certificates
  become: yes
