- name: install packages
  become: yes
  apt:
    name:
      - zsh
    update_cache: yes
    state: present

- name: change user shell to zsh 
  become: yes
  user:
    name: "{{ the_user }}"
    shell: /bin/zsh

- name: oh-my-zsh
  ansible.builtin.shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/"