- name: "**dapr-cli** register status of /usr/local/bin/dapr"
  ansible.builtin.stat: 
    path: "/usr/local/bin/dapr"
  register: dapr_cli_status

- name: "**dapr-cli** install dapr-cli"
  when : dapr_cli_status.stat.exists == False
  block: 
  - name: "dapr-cli: Download dapr-cli install script"
    ansible.builtin.uri:
      url: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
      return_content: yes
    register: dapr_cli_install_script

  - name: "**dapr-cli** run dapr-cli install script"
    ansible.builtin.shell:
      cmd: "{{ dapr_cli_install_script.content }}"
    become: yes 
    args:
      executable: /bin/bash