---
# tasks file for wsl-git-credentials-manager
- name: Install apt packages
  become: yes
  apt:
    name:
      - xdg-utils
    update_cache: yes
    state: present

- name: Download git cred manager gcm-linux_amd64.2.0.886.deb
  become: yes
  ansible.builtin.get_url:
    url: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-linux_amd64.2.0.886.deb
    dest: /var/cache/apt/archives/gcm-linux_amd64.2.0.886.deb
    checksum: sha256:f18e36851c5aa4aacc20beef4ab12eb93c3727bd716e417b0593241d6f580750

- name: Install git cred manager
  become: yes
  apt:
    deb: /var/cache/apt/archives/gcm-linux_amd64.2.0.886.deb

- name: configure git to use get cred manager
  shell: |
    git-credential-manager configure
    git config --global credential.guiPrompt false

- name: Set Credential Manager types and store
  become: yes
  copy:
    content:  |
      export GCM_CREDENTIAL_STORE=cache
      export GCM_AZREPOS_CREDENTIALTYPE="oauth"
    dest: /etc/profile.d/gitconfig.sh

- name: setup git name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: setup git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: setup git default branch
  git_config:
    name: init.defaultbranch
    scope: global
    value: "main"