---
# tasks file for wsl-dev-role


  - name: Check if we have certs to configure
    stat: 
      path: ./certs/wincerts.pem
    register: certs

  - name: Configure Custom Certificates
    when: certs.stat.exists == True
    ansible.builtin.import_tasks: wsl-certificates.yml
  
  - name: shell
    ansible.builtin.import_tasks: config-shell.yml

  - name: Configure Git Credentials Manager using role
    ansible.builtin.import_tasks: git-credentials-manager.yml
  
  - name: setup git name
    git_config:
      name: user.name
      scope: global
      value: "{{ git_username }}"

  - name: setup git user email
    git_config:
      name: user.email
      scope: global
      value: "{{ git_email }}"

  - name: setup git default branch
    git_config:
      name: init.defaultbranch
      scope: global
      value: "main"


  - name: Configure WSL Utilities
    ansible.builtin.import_tasks: wsl-utilities.yml

  - name: Configure Node 
    ansible.builtin.import_tasks: setup-node.yml

  - name: Configure custom certificates for Node and NPM 
    when: certs.stat.exists == True
    ansible.builtin.import_tasks: node-custom-certs.yml

  - name: Custom Dev Libs and tools 
    ansible.builtin.import_tasks: dev-lib-tools.yml

  - name: Python
    ansible.builtin.import_tasks: config-python.yml

  - name: Azure CLI
    ansible.builtin.import_tasks: azure-cli.yml

  - name: Dapr CLI
    ansible.builtin.import_tasks: dapr-cli.yml

  - name: Wireshark
    ansible.builtin.import_tasks: setup-wireshark.yml

  - name: Task
    ansible.builtin.import_tasks: task-cli.yml

  - name: Kubernetes Dev
    ansible.builtin.import_tasks: k8s-dev.yml

  - name: Write .zshrc config
    template:
      src: .zshrc
      dest: "~/.zshrc"
      owner: "{{ ansible_user_id }}"
      backup: yes