---
# tasks file for wsl-dev-role


  - name: Check if we have certs to configure
    stat: 
      path: ./certs/wincerts.pem
    register: certs

  - name: Configure Custom Certificates 
    when: certs.stat.exists == True
    ansible.builtin.import_tasks: wsl-certificates.yml
  
  - name: Configure Oh My Bash
    ansible.builtin.import_tasks: oh-my-bash.yml

  - name: Configure Git Credentials Manager
    ansible.builtin.import_tasks: git.yml
  
  - name: Configure WSL Utilities
    ansible.builtin.import_tasks: wsl-utilities.yml

  - name: Configure Node 
    ansible.builtin.import_tasks: node.yml

  - name: Custom Dev Libs and tools 
    ansible.builtin.import_tasks: dev-lib-tools.yml

  - name: Python
    ansible.builtin.import_tasks: python.yml

  - name: Azure CLI
    ansible.builtin.import_tasks: azure-cli.yml

  - name: Dapr CLI
    ansible.builtin.import_tasks: dapr-cli.yml

  - name: Wireshark
    ansible.builtin.import_tasks: wireshark.yml

  - name: Just
    ansible.builtin.import_tasks: just-cli.yml

  - name: Kubernetes Dev
    ansible.builtin.import_tasks: k8s-dev.yml
