- name: "**node** Install nvm"
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"


- name: "**node** Install node"
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ node_version }}"


- name: "**node** set NODE_EXTRA_CA_CERTS environment variable"
  when: certs.stat.exists == True
  ansible.builtin.blockinfile:  
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    path: /home/{{ ansible_user_id }}/.profile
    block: |
      export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/wincerts.pem


- name: "**node** configure node to use certificates"
  when: certs.stat.exists == True
  become: no
  shell: |
      . {{ ansible_env.HOME }}/.nvm/nvm.sh
      npm config set cafile=/usr/local/share/ca-certificates/wincerts.pem -L user
  args:
    executable: /bin/bash
    