# our bootstrap installs python, but lets put a pointer from python to python3
- name: Install Python
  become: yes
  apt:
    name:
      - python3-pip
      - python-is-python3
      - python3.10-venv
      - python3
    update_cache: yes
    state: present