- name: "**wsl-utilities** Add windows services for linux stable repository from PPA"
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:wslutilities/wslu
    update_cache: no

- name: "**wsl-utilities** Install apt packages"
  become: yes
  apt:
    name:
      - wslu
    update_cache: yes
    state: present