
- name: copy certificates to trusted ca path
  become: yes
  copy:
    src: './certs/'
    dest: '/usr/local/share/ca-certificates/'
    owner: root
    group: root
    mode: 0644

- name: Change encoding for pem file
  become: yes
  shell: 'iconv -f UTF-16LE -t UTF-8 /usr/local/share/ca-certificates/wincerts.pem -o /usr/local/share/ca-certificates/wincerts.pem'

- name: update trusted ca
  shell: /usr/sbin/update-ca-certificates
  become: yes

