---
# tasks file for dev_python
- name: "**python** Install Python"
  become: yes
  apt:
    name:
      - python3-pip
      - python-is-python3
      - python3.10-venv
      - python3
    update_cache: yes
    state: present