---
- name: set NODE_EXTRA_CA_CERTS environment variable
  ansible.builtin.blockinfile:  
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    path: /home/{{ ansible_user_id }}/.profile
    block: |
      export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/wincerts.pem

# - name: Print return information from the previous task
#   become: no
#   ansible.builtin.debug:
#     msg: "here I am -- {{ ansible_env.HOME }}"


- name: Get uptime information
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh 
    npm config ls -l >> out.txt
  args:
    executable: /bin/bash
  register: result  

- debug: var=result

- name: configure node to use certificates
  become: no
  shell: |
      . {{ ansible_env.HOME }}/.nvm/nvm.sh
      npm config set cafile=/usr/local/share/ca-certificates/wincerts.pem -L user
  args:
    executable: /bin/bash