- hosts: localhost
  vars: 
    node_version: 18.16.0

  tasks:
  - name: Check if we have certs to configure
    stat: 
      path: ./certs/wincerts.pem
    register: certs

  - name: Configure Custom Certificates
    when: certs.stat.exists == True
    import_role:
      name: wsl-certificates

  - name: Configure Git Credentials Manager using role
    import_role:
      name: wsl-git-credentials-manager

  - name: Configure WSL Utilities using role
    import_role:
      name: wsl-wsl

  - name: Configure Node using role
    import_role:
      name: wsl-node

  - name: Configure custom certificates for Node and NPM 
    when: certs.stat.exists == True
    import_role:
      name: wsl-node-custom-certs

  # - name: Configure Dev Containers using role
  #   import_role:
  #     name: wsl-devcontainers


  
