- hosts: localhost

  vars: 
    node_version: 18.16.0

  tasks:

  - name: Configure Git Credentials Manager using role
    import_role:
      name: wsl-git-credentials-manager

  - name: Configure WSL Utilities using role
    import_role:
      name: wsl-wsl

  - name: Configure Node using role
    import_role:
      name: wsl-node

  - name: Configure Dev Containers using role
    import_role:
      name: wsl-devcontainers
