- hosts: localhost
  tasks:

  - name: copy certificates to trusted ca path
    copy: 
      src: 'wincerts.pem'
      dest: '/usr/local/share/ca-certificates/'
      owner: root
      group: root
      mode: 0644
    notify: 
      - update trusted ca

  - name: Configure the Package Source (PPM) for node 20
    shell: 'curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -'

  - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
    ansible.builtin.apt_repository:
      repo: ppa:wslutilities/wslu

  - name: Install git cred manager
    apt:
      deb: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-linux_amd64.2.0.886.deb

  - name: Install apt packages
    apt:
      name: 
        - gcc
        - make
        - g++
        - nodejs
        - libsecret-1-0
        - libsm6
        - wslu
      state: present

  - name: configure node to use certificates
    copy:
      content: export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/wincerts.pem
      dest: /etc/profile.d/nodeconfig.sh

  - name: configure node to use certificates
    copy:
      content:  | 
        git-credential-manager configure
        export GCM_CREDENTIAL_STORE=cache
        git config --global credential.guiPrompt false
      dest: /etc/profile.d/gitconfig.sh

  - name: "Install NPM-distributed command-line tools"
    npm:
      global: yes
      name: "{{ item }}"
    with_items:
      - "@devcontainers/cli"

  # - name: Disable Windows Interop
  #   copy:
  #     dest: "/etc/wsl.conf"
  #     content: |
  #       [interop]
  #       enabled = false
  #       appendWindowsPath = false

  handlers: 
  - name: update trusted ca
    shell: /usr/sbin/update-ca-certificates