- hosts: localhost
  tasks:

  - name: Check if we have certs to configure
    stat: 
      path: ./certs/wincerts.pem
    register: p

  - name: Configure Custom Certificates
    block: 

    - name: copy certificates to trusted ca path
      copy:
        src: './certs/'
        dest: '/usr/local/share/ca-certificates/'
        owner: root
        group: root
        mode: 0644

    - name: Change encoding for pem file
      shell: 'iconv -f UTF-16LE -t UTF-8 /usr/local/share/ca-certificates/wincerts.pem -o /usr/local/share/ca-certificates/wincerts.pem'

    - name: update trusted ca
      shell: /usr/sbin/update-ca-certificates
      become: yes

    - name: configure node to use certificates
      copy:
        content: |
          export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/wincerts.pem
        dest: /etc/profile.d/nodeconfig.sh

    - name: Creates directory
      file:
        path: /usr/etc
        state: directory

    - name: configure NPM to use certificates
      copy:
        content: |
          cafile=/usr/local/share/ca-certificates/wincerts.pem
        dest: /usr/etc/npmrc

    when: p.stat.exists == True

  - name: Configure PPA for Node and WSLU
    block: 

    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: "Add nodejs 20.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_20.x jammy main
        update_cache: no

    - name: Add windows services for linux stable repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:wslutilities/wslu
        update_cache: no

  - name: Install Git Credential Manager
    block: 
    - name: Download git cred manager gcm-linux_amd64.2.0.886.deb
      ansible.builtin.get_url:
        url: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-linux_amd64.2.0.886.deb
        dest: /var/cache/apt/archives/gcm-linux_amd64.2.0.886.deb
        checksum: sha256:f18e36851c5aa4aacc20beef4ab12eb93c3727bd716e417b0593241d6f580750

    - name: Install git cred manager
      apt:
        deb: /var/cache/apt/archives/gcm-linux_amd64.2.0.886.deb

    - name: configure git to use get cred manager
      copy:
        content:  |
          git-credential-manager configure
          export GCM_CREDENTIAL_STORE=cache
          git config --global credential.guiPrompt false
        dest: /etc/profile.d/gitconfig.sh

  - name: Install apt packages
    apt:
      name:
        - gcc
        - make
        - g++
        - nodejs
        - libsecret-1-0
        - libsm6
        - wslu
      update_cache: yes
      state: present

  - name: "Install NPM-distributed command-line tools"
    npm:
      global: yes
      name: "{{ item }}"
    with_items:
      - "@devcontainers/cli"
