- hosts: localhost
  vars: 
    node_version: 18.16.0
    git_username: "Brian Olson"
    git_email: "beolson@hero4hire.com"

  tasks:
  - name: Check if we have certs to configure
    stat: 
      path: ./certs/wincerts.pem
    register: certs

  - name: Configure Custom Certificates
    when: certs.stat.exists == True
    import_role:
      name: wsl-certificates

  - name: Configure Git Credentials Manager using role
    import_role:
      name: wsl-git-credentials-manager

  - name: setup git name
    git_config:
      name: user.name
      scope: global
      value: "{{ git_username }}"
      
  - name: setup git user email
    git_config:
      name: user.email
      scope: global
      value: "{{ git_email }}"

  - name: Configure WSL Utilities using role
    import_role:
      name: wsl-wsl

  - name: Configure Node using role
    import_role:
      name: wsl-node

  - name: Configure custom certificates for Node and NPM 
    when: certs.stat.exists == True
    import_role:
      name: wsl-node-custom-certs

  - name: Custom Dev Libs 
    import_role:
      name: wsl-native-dev-lib

  # - name: Configure Dev Containers using role
  #   import_role:
  #     name: wsl-devcontainers


  
