---
# tasks file for wsl-git-credentials-manager
- name: "Install apt packages"
  become: yes
  ansible.builtin.apt:
    name:
      - xdg-utils
    update_cache: yes
    state: present

- name: "Install git cred manager"
  become: yes
  ansible.builtin.apt:
    deb: https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-linux_amd64.2.0.886.deb

- name: "configure git to use get cred manager"
  ansible.builtin.shell: |
    git-credential-manager configure
    git config --global credential.guiPrompt false

- name: "Set Credential Manager types and store"
  become: yes
  ansible.builtin.copy:
    content:  |
      export GCM_CREDENTIAL_STORE=cache
      export GCM_AZREPOS_CREDENTIALTYPE="oauth"
    dest: /etc/profile.d/gitconfig.sh

- name: "setup git name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"

- name: "setup git user email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"

- name: "setup git default branch"
  community.general.git_config:
    name: init.defaultbranch
    scope: global
    value: "main"